[package]
name = "mystiproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.3.1", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
http-body-util = "0.1.1"
hyper-util = { version = "0.1.5", features = ["http1", "http2", "tokio", "server-graceful", "server-auto"] }
bytes = "1.6.0"
form_urlencoded = "1.1.1"
clap = { version = "4.5.6", features = ["derive"] }
futures = { version = "0.3", features = ["async-await"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
regex = "1.5.4"
log = "0.4"
env_logger = "0.9"
chrono = {  version = "0.4", features = ["serde"] }
kube = { version = "0.93.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.22.0", features = ["latest"] }


[dev-dependencies]
test-case = "1"

