[package]
name = "tuds"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.3.1", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
http-body-util = "0.1.1"
hyper-util = { version = "0.1.5", features = ["full"] }
bytes = "1.6.0"
form_urlencoded = "1.1.1"
clap = { version = "4.5.6", features = ["derive"] }
futures = { version = "0.3", features = ["async-await"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5.4"

[dev-dependencies]
test-case = "1"

