service:
  - name: docker
    listen: '127.0.0.1:10000'
    protocol: uds+http
    timeout: 10s
    target: /var/run/docker.sock
    http:
      request:
        uri: # 可能需要定义为uriMapping
          path: { }
          query: { }
        headers:
          Host:
            value: localhost
            action: 'overwrite' # 默认值，强制复写
            condition: '' # 条件，为true才会执行
          forward-host:
            value: localhost
            action: 'missed' # 缺少，则添加
          x-host:
            action: 'forceDelete' # 有就删除
        body: # 只支持json，并使用jsonpath进行处理
          json:
            '$.name':
              value: 'test'
              action: 'overwrite'
              condition: ''
      response:
        headers:
          Host:
            value: localhost
            action: 'overwrite' # 默认值，强制复写
            condition: '' # 条件，为true才会执行
        body:
          json:
            '$.name':
              value: 'test'
              action: 'overwrite'
              condition: ''

  - name: server
    listen: "127.0.0.1:100001"
    protocol: 'tcp+https'
    timeout: 10s
    target: "192.168.1.1:5244"
    http:
      request:
        headers:
          Host:
            value: '192.168.1.1'
            action: ''
      response:
        headers: { }