[package]
name = "http_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
test-case = "*"
