#[build]
#target = "x86_64-unknown-linux-gnu"

#[target.x86_64-unknown-linux-musl]
#rustflags = ["-C", "link-arg=-Wl,-z,relro,-z,now"]

[target.wasm32-unknown-emscripten]
rustflags = ["--cfg", "wasmedge", "--cfg", "tokio_unstable"]
