name: Build and Archive

on:
  workflow_call:
    inputs:
      target:
        description: 'The target triple for the build'
        required: true

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
    - name: Get Git Commit ID
      id: git_commit
      run: echo "GIT_COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
    - name: Build Release
      run: cargo build --release --target ${{ inputs.target }}
    - name: Archive Release Build as ZIP
      run: |
        cd target/${{ inputs.target }}/release
        if [ "$RUNNER_OS" == "Windows" ]; then
          Compress-Archive -Path mystiproxy.exe -DestinationPath mystiproxy-${{ inputs.target }}-${{ env.GIT_COMMIT_ID }}.zip
        else
          zip -r mystiproxy-${{ inputs.target }}-${{ env.GIT_COMMIT_ID }}.zip mystiproxy
        fi
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mystiproxy-${{ inputs.target }}-${{ env.GIT_COMMIT_ID }}.zip
        path: target/${{ inputs.target }}/release/mystiproxy-${{ inputs.target }}-${{ env.GIT_COMMIT_ID }}.zip
