name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Get Git Commit ID
      id: git_commit
      run: echo "GIT_COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
    - name: Archive Release Build as ZIP
      run: |
        cd target/release
        zip -r mystiproxy-${{ env.GIT_COMMIT_ID }}.zip mystiproxy
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mystiproxy-${{ env.GIT_COMMIT_ID }}.zip
        path: target/release/mystiproxy-${{ env.GIT_COMMIT_ID }}.zip